---
- job:
    name: tflint
    parent: golang-make
    vars:
      make_command: tflint

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - tflint
    gate:
      jobs:
        - tflint
