---
- job:
    name: project-factory-tflint
    parent: golang-make
    vars:
      make_command: tflint

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - project-factory-tflint
        - otc-terraform-module-publish
    gate:
      jobs:
        - project-factory-tflint
