---
- job:
    name: modules-tflint
    parent: golang-make
    vars:
      make_command: tflint

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - modules-tflint
        - otc-terraform-module-publish
    gate:
      jobs:
        - modules-tflint
